### PR TITLE
update deps, fix config warnings

### PR DESCRIPTION
**Pull request by ayrat555**

### CODE REVIEW

**Comment by ayrat555** [comment]
@ulissesalmeida hello! can you please take a look?

**Comment by ulissesalmeida** [comment]
@ayrat555 

Sure! Thank you for your contribution.

I can see there are 4 major changes here:

1. Supporting Elixir latest version
2. Deprecate older Elixir version by using `import Config`
3. Dependabot addition
4. GitHub Actions migration

Would you mind splitting these changes on different PRs?

I think it's alright to do 1 + 2 in a single PR.

The 3. and 4. I would like to address them on different PRs. 

The 4), GitHub Actions migration:
Isn't clear to me why we should stop using CircleCI, is there anything on CircleCi that is impossible to do without GitHub actions? I had a local branch that I was planning to migrate to Earthly and use a `Earthfile` like in ecto. Example:
https://github.com/elixir-ecto/ecto/blob/master/Earthfile
I never finish that, but one day I'll do. That's why I'm not totally inclined to do pure Github Actions.


Thank you again for coming and suggesting these changes.

**Comment by ayrat555** [comment]
@ulissesalmeida I separated this pr into:
- https://github.com/ulissesalmeida/cpf/pull/8 - fix deprecation warnings, update deps
- https://github.com/ulissesalmeida/cpf/pull/9 - add dependabot

for now I didn't create a github actions config. personally I think it's easier to use because doesn't use external integrations.

**Comment by ulissesalmeida** [comment]
@ayrat555 The `v1.2.0` is out, thank you 🎉

**Comment by ulissesalmeida** [comment]
https://hex.pm/packages/cpf/1.2.0

**Pull request closed without merging**
